version: '3'

services:
  api:
    image: node:18
    working_dir: /tag-manager/api
    volumes:
      - ./:/tag-manager
      - ./datasets:/datasets
    ports:
      - 4000:4000
    command: bash -c "curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm && pnpm install && pnpm run dev"

  app:
    image: node:18
    working_dir: /tag-manager/app
    volumes:
      - ./:/tag-manager
    ports:
      - 5173:5173
    command: bash -c "curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm && pnpm install && pnpm run dev"
