version: '3'

services:
  api:
    image: node:18
    working_dir: /api
    volumes:
      - ./api:/api
      - ./datasets:/datasets
    ports:
      - 4000:4000
    command: bash -c "curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm && pnpm install && pnpm run dev"

  app:
    image: node:18
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 5173:5173
    command: bash -c "curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm && pnpm install && pnpm run dev"
